#version: '4.3'

#services:
#  database:
#    image: mysql:8.0
#    container_name: mysql_erudio
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'rest_with_spring_boot_erudio_db'
#      MYSQL_USER: 'docker'
#      MYSQL_PASSWORD: 'docker'
#      MYSQL_ROOT_PASSWORD: 'admin'
#    ports:
#      - '3306:3306'

version: '3.9'
services:
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: rest_with_spring_boot_erudio_db
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - erudio-network

  rest-with-spring-boot-erudio:
    # imagem no docker hub (luucasdinoo)
    image: luucasdinoo/rest-with-spring-boot-erudio
    restart: always
    build: ./rest-with-spring-boot-and-java-erudi
    working_dir: /rest-with-spring-boot-and-java-erudio
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/rest_with_spring_boot_erudio_db?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - erudio-network

networks:
  erudio-network:
    driver: bridge

