spring:
  application:
    name: rest_with_spring_boot_erudio

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio_db?useTimezone=true&serverTimezone=UTC
    username: docker
    password: docker

  jpa:
    hibernate:
      ddl-auto: none
    show_sql: false
    open-in-view: false

spring-doc:
  # Documentar apenas os endpoints informados abaixo
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true
